#pragma once

#define CAPS_WORD_IDLE_TIMEOUT 2000
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define USB_POLLING_INTERVAL_MS 1

// Hold-Tap 
#define TAPPING_TERM 250
#define PERMISSIVE_HOLD
#define FLOW_TAP_TERM 80
#define CHORDAL_HOLD
#define SPECULATIVE_HOLD

// Autoshift
#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_ALPHA
#define NO_AUTO_SHIFT_SPECIAL

#ifdef COMBO_ENABLE
#	define EXTRA_SHORT_COMBOS
#	define COMBO_TERM_PER_COMBO
#	define COMBO_SHOULD_TRIGGER
#	define COMBO_ONLY_FROM_LAYER 0
#endif

